DataObject:
  extensions:
    - EncryptDataObjectFieldsExtension
EncryptDataObjectFieldsExtension:
  EncryptedDataObjects:
    - EncryptDataObject
File:
  allowed_extensions:
    - enc

---
Only:
  classexists: 'SecureFileController'
---
#Defined only if the secureassets module is installed:
SecureFileController:
  extensions:
    - EncryptedSecureFileControllerExtension
